### ISSUE TITLE
Injected env comes in as name@azurekeyvault instead of actual value

### ISSUE THREAD

**Issue by benrjnih** [SparebankenVest/azure-key-vault-to-kubernetes#1]
I went through the installation steps detailed in the README, and all appeared to work fine, but when I go to grab the injected secret, the application sees it as `my-secret-ci-env@azurekeyvault` instead of the actual value from Azure Key Vault.  

What would this mean?

My yaml:
```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: my-secret-ci-env
  namespace: default
spec:
  vault:
    name: my-dev-kv
    object:
      type: secret
      name: CI-ENV
```
and in my deployment:

```
        env:
        - name: CI_ENV
          value: my-secret-ci-env@azurekeyvault
```

And in my PHP application:
```
echo 'CI_ENV: ' . $_ENV['CI_ENV'];
```
Which displays: `CI_ENV: my-secret-ci-env@azurekeyvault`

Am I missing something?  Is there a place to find logs to see if the azure secret is being retrieved correctly?
