### ISSUE TITLE
Key injection not working on second deployment

### ISSUE THREAD

**Issue by hisuwh** [SparebankenVest/azure-key-vault-to-kubernetes#11]
I have setup the azure-key-vault-to-kubernetes integration and have got this working with one deployment.  I have now added another deployment that I want settings injected into and it is not working despite these being set up almost identically.

This is the error I am getting:

```batch
level=fatal msg="env-injector: error getting azurekeyvaultsecret resource 'qat-encryption-certificate', error: Get https://app-dev-a--app-dev-aks-1c7826-ac6b8c6e.hcp.northeurope.azmk8s.io:443/apis/spv.no/v1alpha1/namespaces/default/azurekeyvaultsecrets/qat-encryption-certificate: EOF"
```
---

So I have setup the controller and pods and they are running (in a namespace `key-vault`:
![image](https://user-images.githubusercontent.com/4470351/61803619-6b166500-ae2a-11e9-9ed5-f7f45611418f.png)

My secrets are defined as follows:
```yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: qat-encryption-certificate
  namespace: default
spec:
  vault:
    name: appvault
    object:
      name: qat-encryption-certificate
      type: certificate
  output:
    secret:
      name: qat-encryption-certificate
      type: kubernetes.io/tls
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: qat-storage-connection-string
  namespace: default
spec:
  vault:
    name: appvault
    object:
      name: qat-storage-connection-string
      type: secret
  output:
    secret:
      name: qat-storage-connection-string
      dataKey: azuresecret
```

I have setup my namespaces like this:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: key-vault
  labels:
    azure-key-vault-env-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    azure-key-vault-env-injection: enabled
---
```

My first deployment which is working is defined like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-app-api-qat
  labels:
    oem: app
    app: app-api
    env: qat
    tier: backend
spec:
  replicas: 2
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: company-app-api-qat
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: company-app-api-qat
    spec:
      containers:
      - name: company-serviceapi
        image: appsharedcontaineregistryeun.azurecr.io/company-api:25603
        env:
        - name: AzureStorageConnectionString
          value: qat-storage-connection-string@azurekeyvault
        - name: Encryption__PublicKey
          value: qat-encryption-certificate@azurekeyvault?tls.crt
        - name: Encryption__PrivateKey
          value: qat-encryption-certificate@azurekeyvault?tls.key
        resources:
          requests:
            memory: 512Mi
            cpu: "0.25"
          limits:
            memory: 512Mi
            cpu: "0.5"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: acr-auth
```

My second deployment is defined like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-app-app1-qat
  labels:
    oem: app
    app: app-app1
    env: qat
    tier: backend
spec:
  replicas: 2
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: company-app-app1-qat
  template:
    metadata:
      labels:
        app: company-app-app1-qat
    spec:
      containers:
      - name: company-app1
        image: appsharedcontaineregistryeun.azurecr.io/company-app1:25606
        env:
        - name: AzureWebJobsStorage
          value: qat-storage-connection-string@azurekeyvault
        - name: Encryption__PublicKey
          value: qat-encryption-certificate@azurekeyvault?tls.crt
        - name: Encryption__PrivateKey
          value: qat-encryption-certificate@azurekeyvault?tls.key
        resources:
          requests:
            memory: 512Mi
            cpu: "0.25"
          limits:
            memory: 512Mi
            cpu: "0.25"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      - name: app2
        image: appsharedcontaineregistryeun.azurecr.io/company-app2:25606
        resources:
          requests:
            memory: 512Mi
            cpu: "0.25"
          limits:
            memory: 512Mi
            cpu: "0.5"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: acr-auth
```

The `copy-azurekeyvault-env` Init containers exists for the pods in both deployments.

Why would I get this error in one but not the other.  Is there are way I can debug this further?  

Looking at the logs for the injector I can see it happily mutating the containers and finding the env vars to replace.

I can see the controller is happily synching the secrets and I can see the secrets:

![image](https://user-images.githubusercontent.com/4470351/61804888-a87bf200-ae2c-11e9-85a4-0d799845ac38.png)

**Comment by torresdal** [comment]
Sorry for the late response. This seams strange. Could you provide the logs for the env-injector?

**Comment by hisuwh** [comment]
I actually have a sort of solution for this.  It seems like it was probably istio blocking the request for the secrets.

Our first deployment had this and adding this to second allowed the injector to work properly:
```yaml
template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
```

This is still strange though as I would expect the request from the injector for the secrets to be internal to the cluster and therefore istio should not be involved.  The url in my original post seems to be a public url though which is strange
```
https://app-dev-a--app-dev-aks-1c7826-ac6b8c6e.hcp.northeurope.azmk8s.io:443/apis/spv.no/v1alpha1/namespaces/default/azurekeyvaultsecrets/qat-encryption-certificate
```

Is there no way for the injector to request the secrets internally to the cluster and save us having to open up egress?
