### ISSUE TITLE
Secret with multiple entries in data field

### ISSUE THREAD

**Issue by heikostumpf** [SparebankenVest/azure-key-vault-to-kubernetes#14]
Hello,

I am deploying istio using helm into my cluster. The chart requires a Secret with "username" and "passphrase" in the data section. At the moment I am only able to create a Secret with one single data entry. Can you please guide me how to configure the AzureKeyVaultSecret to achieve this?

This example shows the final Secret I want to create with AzureKeyVaultSecret.
```
##
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: istio
  labels:
    app: grafana
type: Opaque
data:
  username: ...
  passphrase: ...
```

Thanks!
