### ISSUE TITLE
[BUG] : Environment Inject is not working in Init Containers

### ISSUE THREAD

**Issue by pvmraghunandan** [SparebankenVest/azure-key-vault-to-kubernetes#141]
**Description**

We are trying to inject key vault secrets to Init Container for doing few shell operations. Unfortunately, we couldn't make it work. Init container is always stuck. We tried checking environment injector logs and not much info or activity there.

**To Reproduce**
Below is the sample YAML File

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: com-test-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      volumes:
        - name: sample
          emptyDir: {}
      initContainers:
      - name: init-test
        image: busybox
        command: ['sh', '-c', 'echo "$test" > "/opt/sample/test";']
        volumeMounts:
        - name: testvolume
          mountPath: /opt/sample
        env:
        - name: test
          value: "testsecret@azurekeyvault" # ref to akvs
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sample
          mountPath: /opt/sample
```

**Expected behavior**
Init Container should have secrets injected.
