### ISSUE TITLE
[BUG] multi-key-value-secret does not work as it was

### ISSUE THREAD

**Issue by ChaosGramer** [SparebankenVest/azure-key-vault-to-kubernetes#143]
**Components and versions**
Select which component(s) the bug relates to with [X].

[ x ] Controller, version: `1.1.0` (docker image tag)
[ ] Env-Injector (webhook), version: `x.x.x` (docker image tag)
[ ] Other

**Describe the bug**
Previous to v1.1.0 if you were using `multi-key-value-secret` the keys were exported from the json / yaml in the azure key vault.
Now dataKey seems to be a required value. providing this value leads to have the json / yaml as value of the key in the resulting secret

**To Reproduce**
1. create secret in key vault. Content: 
```json
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}
```
2. create azure key vault without data key: 
```yaml
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  annotations:
  name: db-config
spec:
  output:
    secret:
      name: db-config
      type: multi-key-value-secret
  vault:
    name: <your-vault>
    object:
      contentType: application/x-json
      name: db-config
      type: secret
```
3. Check the logs in controller: 
```
time="2020-10-23T08:08:48Z" level=error msg="error syncing 'testing/db-config': failed to get secret from Azure Key Vault for secret 'testing'/'db-config', error: no datakey spesified for output secret, requeuing
```

Following the error, I tried creating a AKVS with the `dataKey` property. 
1. new yaml: 

```yaml
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  annotations:
  name: db-config
spec:
  output:
    secret:
      name: db-config
      type: multi-key-value-secret
      dataKey: awesome
  vault:
    name: hcbae2i01kvtsec001
    object:
      contentType: application/x-json
      name: db-config
      type: secret
```
2. resulting secret in the cluster: 
```yaml
apiVersion: v1
data:
  awesome: eyAgICJrZXkxIjogInZhbHVlMSIsICAgImtleTIiOiAidmFsdWUyIiwgICAia2V5MyI6ICJ2YWx1ZTMiIH0=
kind: Secret
metadata:
  name: db-config
  namespace: testing
  ownerReferences:
  - apiVersion: spv.no/v1
    blockOwnerDeletion: true
    controller: true
    kind: AzureKeyVaultSecret
    name: db-config
type: multi-key-value-secret
```
**Expected behavior**
I would expect that the result of the multi-key-value-secret would look like this: 
```yaml
apiVersion: v1
data:
  key1: dmFsdWUx
  key2: dmFsdWUy
  key3: dmFsdWUz
kind: Secret
metadata:
  name: db-config
  namespace: testing
  ownerReferences:
  - apiVersion: spv.no/v1
    blockOwnerDeletion: true
    controller: true
    kind: AzureKeyVaultSecret
    name: db-config
type: multi-key-value-secret
```

**Comment by torresdal** [comment]
Thanks @ChaosGramer - I'll have a look and see what I find. Any theories about what it could be?

**Comment by ChaosGramer** [comment]
No I have not watched into the code, I just wanted to open a PR on the documentation page. Whilst testing, what I was writing I spottet this behaviour.

**Comment by torresdal** [comment]
About docs. Note that I moved it into a separate repo yesterday called akv2k8s-website.

**Comment by torresdal** [comment]
I see - the feature probably works, but validation is off. Hopefully won't take long to find and fix.

**Comment by torresdal** [comment]
@ChaosGramer looks like I merged your pr a bit too quickly. Looking at your test case above, I see you specify:

```yaml
output:
    secret:
      type: multi-key-value-secret
```

It's not the output secret type that should be `multi-key-value-secret`, but the vault object type:

```yaml
vault:
    name: hcbae2i01kvtsec001
    object:
      contentType: application/x-json
      name: db-config
      type: multi-key-value-secret
```

Reason for the issue you get, is that the kubernetes secret type of `multi-key-value-secret` is unknown and therefore requires a dataKey
