### ISSUE TITLE
help on keyvault-controller with aad-pod-identity

### ISSUE THREAD

**Issue by smartpcr** [SparebankenVest/azure-key-vault-to-kubernetes#15]
Hi, I am trying to follow instruction to get keyvault-controller to work. Here is what I did:
1. install aad-pod-identity
2. created user-assigned-identity `compes-bedrock-kv-reader`, grant appropriate permissions
3. turn on customAuth, set podIdentitySelector to `kv-reader`
4. created AzureIdentity and AzureIdentityBinding
5. create AzureKeyVaultSecret

I can see azurekeyvaultcontroller is created and running, but secrets is not created, can you point me to logs where to trouble shoot. 

- AzureKeyVaultSecret 
``` yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: tls-cert
  namespace: {{.Values.namespace}}
spec:
  vault:
    name: {{.Values.vault_name}}
    object:
      name: {{.Values.tls_cert_secret_name}}
      type: certificate
  output:
    name: tls-cert
```

- AzureIdentity
``` yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: pod-identity
spec:
  type: 0
  ResourceID: /subscriptions/{{.Values.subscription_id}}/resourcegroups/<resourcegroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{.Values.pod_identity_name}}
  ClientID: {{.Values.pod_identity_client_id}}
```
- AzureIdentityBinding
``` yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: pod-identity-binding
spec:
  AzureIdentity: pod-identity
  Selector: {{.Values.pod_identity_selector}}
```
- values.yaml
``` yaml
subscription_id: ***
pod_identity_client_id: ***
pod_identity_selector: kv-reader
pod_identity_name: compes-bedrock-kv-reader
```

- kubectl describe pod keyvault-controller-azure-key-vault-controller-6c59664544-n4j94 -n security
``` bash
Name:               keyvault-controller-azure-key-vault-controller-6c59664544-n4j94
Namespace:          security
Priority:           0
PriorityClassName:  <none>
Node:               aks-default-33055681-0/10.240.0.4
Start Time:         Tue, 20 Aug 2019 14:26:23 -0700
Labels:             aadpodidbinding=kv-reader
                    app=azure-key-vault-controller
                    pod-template-hash=6c59664544
                    release=keyvault-controller
Annotations:        <none>
Status:             Running
IP:                 10.244.1.20
Controlled By:      ReplicaSet/keyvault-controller-azure-key-vault-controller-6c59664544
Containers:
  azure-keyvault-controller:
    Container ID:  docker://9b8f25938a798d8b99119596422f1a32a101bd95d25e46edc5a6d2b911ff2801
    Image:         spvest/azure-keyvault-controller:0.1.14
    Image ID:      docker-pullable://spvest/azure-keyvault-controller@sha256:332425e3983a0bac3595746d8a6bd343a9dbe6593ab1c3309b6a3ba953423dde
    Port:          <none>
    Host Port:     <none>
    Args:
      --cloudconfig=/etc/kubernetes/azure.json
    State:          Running
      Started:      Tue, 20 Aug 2019 14:26:28 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      AZURE_VAULT_NORMAL_POLL_INTERVALS:     1m
      AZURE_VAULT_EXCEPTION_POLL_INTERVALS:  10m
      AZURE_VAULT_MAX_FAILURE_ATTEMPTS:      5
      AAD_POD_BINDING_LABEL:                  (v1:metadata.labels['aadpodidbinding'])
      CUSTOM_AUTH:                           true
      LOG_LEVEL:                             info
    Mounts:
      /etc/kubernetes/azure.json from azure-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from keyvault-controller-azure-key-vault-controller-token-57xx6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure-config:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  keyvault-controller-azure-key-vault-controller-token-57xx6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  keyvault-controller-azure-key-vault-controller-token-57xx6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

### results

```bash
kubectl get azurekeyvaultsecret
No resources found.
```
