### ISSUE TITLE
[BUG] secret output transform does not work

### ISSUE THREAD

**Issue by mpmatti** [SparebankenVest/azure-key-vault-to-kubernetes#151]
**Components and versions**
Select which component(s) the bug relates to with [X].

[X] Controller, version: `1.1.0` (docker image tag)
[X] Other: chart version 1.1.26 and latest available CRD:
https://raw.githubusercontent.com/sparebankenvest/azure-key-vault-to-kubernetes/master/crds/AzureKeyVaultSecret.yaml

**Describe the bug**
secret output transfrom using base64decode seems not working anymore, after we upgraded the CRDs. Earlier, it used to work with a setup like this:

Azure Key Vault secret named 'dummy' created, content 'dummy', as base64-encoded.
In AKS kubernetes version 1.17.11 cluster, 'kubectl apply' the following:

dummy.yaml:

```
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: helm-example-dummy
  namespace: default
spec:
  vault:
    name: keyvault-for-testing
    object:
      name: dummy
      type: secret
  output:
    transforms:
      - base64decode
    secret:
      name: helm-example-dummy
      type: Opaque
      dataKey: dummy
```

Now, after installing it to a new kubernetes kluster running version 1.19.3 and latest CRD, seems 'transforms' has changed to 'transform':
```
kubectl apply -f dummy.yaml
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(AzureKeyVaultSecret.spec.output): unknown field "transforms" in no.spv.v1.AzureKeyVaultSecret.spec.output
```

Changed 'transforms' to 'transform' in dummy.yaml':
```
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: helm-example-dummy
  namespace: default
spec:
  vault:
    name: keyvault-for-testing
    object:
      name: dummy
      type: secret
  output:
    transform:
      - base64decode
    secret:
      name: helm-example-dummy
      type: Opaque
      dataKey: dummy
```

Now, running 'kubectl apply -f dummy.yaml', which creates akvs-object and synchronizes the secret successfully from key vault. However, it does not base64 decode the secret:
```
$> kubectl get secret helm-example-dummy -o yaml |egrep ' dummy:' |awk '{print $2}' |base64 --decode
ZHVtbXkK
```
Only after another decoding, the content is revealed:
```
$> kubectl get secret helm-example-dummy -o yaml |egrep ' dummy:' |awk '{print $2}' |base64 --decode |base64 --decode
dummy
```

**To Reproduce**
As described above.

**Expected behavior**
The azure keyvault secret is base64-decoded once synced as kubernetes secret.
