### ISSUE TITLE
[FEATURE]: Support for secrets stored in to Azure KeyVault in base64 encoded format

### ISSUE THREAD

**Issue by jaakkos** [SparebankenVest/azure-key-vault-to-kubernetes#20]
First of all, thanks for open-sourcing this tool, there aren't that many good solutions for syncing secrets between Azure KeyVault and Kubernetes secrets.

We are running lots of small microservices written in JVM languages like Clojure and Kotlin. The standard format for storing certificates and keys in the JVM realm is Java KeyStore, aka JKS. Azure KeyVault doesn't support JKS as input format so we have using base64 encoding to go around the limitation so that we can still use KeyVault as the master for all JKS files. Syncing them to Kubernetes secrets remains a bit hazle, and this would simplify the process a lot. Of course this abroach could be used to any files, not only JKS.

I forked the project and created a feature branch to test out syncing base64 encoded KeyVault secrets to Kubernetes secrets, and it seems to work pretty nicely. My approach was to define a new type for vault object ```base64-encoded-secret``` which then can be mounted as a file using volume mounts. 

The full example of my suggestion:
```
  - apiVersion: spv.no/v1alpha1
    kind: AzureKeyVaultSecret
    metadata:
      name: trust-store-jks
      labels:
        kv-secrets: trust-store-jks
    spec:
      vault:
        name: development-kv
        object:
          name: trust-store-jks
          type: base64-encoded-secret
      output:
        secret:
          name: trust-store-jks
          dataKey: trust-store.jks

  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: example
    spec:
      replicas: 1
      ...
        spec:
          containers:
            - name: example
              image: example
              volumeMounts:
                - name: trust-store-jks
                  mountPath: /etc/trust-store
          volumes:
            - name: trust-store-jks
              secret:
                secretName: trust-store-jks
```

What do you think about this approach? Are there any apparent disadvantages with the approach?
Would you be interested in accepting this kind new feature?

I'll soon clean up my feature branch and open pull request regarding this feature request. So that we have more beef around bones to talk about. 😄

**Comment by jaakkos** [comment]
I created draft pull request https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/pull/21 to help with the discussion.

**Comment by jaakkos** [comment]
I updated the pull request to have sensible commits with documentation. 

@torresdal have you had time to check the proposed idea? 😅

**Comment by torresdal** [comment]
@jaakkos Thanks for your pull request and feature. I’m looking at it now. Will get back to you shortly.

**Comment by torresdal** [comment]
@jaakkos just to make sure I understand your requirements correctly. 

1. You have stored base64 encoded secrets in AKV
2. You want the base64 encoded secret in AKV to be decoded by akv2k8s before it gets injected as env var, or created as a k8s secret

Correct?

If it is, I’m thinking it’s more about how the user wants to format the output (decode in this case), than the actual object in AKV - which is just a secret. 

We have a similar case for certificates, where sometimes you will want the raw binary format (for PFX), cause that’s what the .net framework expects. 

Suggestion: what if we allow different output formats instead? (spec.output.secret.type). Today we support the built-in types from k8s (default opaque) like tls. We can just add base64decoded. 

What do you think?

**Comment by torresdal** [comment]
@vidarw thoughts? 👆

**Comment by jaakkos** [comment]
> @jaakkos just to make sure I understand your requirements correctly.
> 
> 1. You have stored base64 encoded secrets in AKV
> 2. You want the base64 encoded secret in AKV to be decoded by akv2k8s before it gets injected as env var, or created as a k8s secret
> 
> Correct?

Yes.

> 
> If it is, I’m thinking it’s more about how the user wants to format the output (decode in this case), than the actual object in AKV - which is just a secret.
> 
> We have a similar case for certificates, where sometimes you will want the raw binary format (for PFX), cause that’s what the .net framework expects.
> 
> Suggestion: what if we allow different output formats instead? (spec.output.secret.type). Today we support the built-in types from k8s (default opaque) like tls. We can just add base64decoded.
> 
> What do you think?

That could also be a good solution. I played with that idea when I was trying out different approaches. The current implementation was most straightforward to test the concept. Should we define the contentType for the vault object or the output? How about something like?


```yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: base64decoded-binary-file
  namespace: my-kw
spec:
  vault:
    name: my-kv
    object:
      name: my-kv
      type: secret
      contentType: base64decoded
  output: 
    secret: 
      name: not-anymore-base64decoded
      dataKey: my-kv.jks

**Comment by torresdal** [comment]
I was thinking about the `output`. The `spec.object` part is meant to only define what akv2k8s needs in order to get the object from akv.

Thinking a bit more about this case, I see we have multiple requests we can solve by introducing a "transformer", including yours.

What I suggest for your case is using a base64decode transformer, like below (the example also shows `trim`-transformer:

```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: base64decoded-binary-file
  namespace: my-kw
spec:
  vault:
    name: my-kv
    object:
      name: my-kv
      type: secret
  output:
    transform:
      - base64decode
      - trim
    secret: 
      name: not-anymore-base64decoded
      dataKey: my-kv.jks
```

If this sounds ok to you and will solve your case, we will start implementing this asap.
