### ISSUE TITLE
Feature: All Objects

### ISSUE THREAD

**Issue by cemo** [SparebankenVest/azure-key-vault-to-kubernetes#212]
**Is your feature request related to a problem? Please describe.**
We spend a lot of time editing configuration files. 

**Describe the solution you'd like**

I would like to enable a property to fetch all secrets and mount them as in their declaration with a prefix.
instead of this:
```
  vault:
    name: akv2k8s-test # name of key vault
    object:
      name: my-secret # name of the akv object
      type: secret # akv object type
```
I prefer this:
```
  vault:
    name: akv2k8s-test # name of key vault
    all_objects: true
    objects_prefix: 'prop.' 
```

Since our key value stores are application based and keeping not thousands of secrets, In case a change in our key value store, I prefer to not edit my yaml files. I prefer to configure once and getting risk to expose something unintended.
