### ISSUE TITLE
[Question] How to sync containter registry token from Azure Key Vault to k8s secret

### ISSUE THREAD

**Issue by jackchuong** [SparebankenVest/azure-key-vault-to-kubernetes#250]
I have registry-container-secret.yaml , works fine, k8s secret "registry-container-secret" is created
```
apiVersion: v1
kind: Secret
metadata:
  name: registry-container-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: xxx
```
I want to sync containter registry token from Azure Key Vault to k8s secret, but I don't know how
This is my registry-container-secret-akv.yaml
```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: registry-container-secret-akv
spec:
  vault:
    name: mykeyvault # name of key vault
    object:
      name: registry-gitlab-secret-akv # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: registry-gitlab-secrets-akv # kubernetes secret name
      type: kubernetes.io/dockerconfigjson
      dataKey: .dockerconfigjson
```
I created an Azure Key Vault secret "registry-container-secret-akv" with value "xxx" or ".dockerconfigjson: xxx" but it doesn't work, secret registry-gitlab-secrets-akv is not created.
Some information
```
NAME                                                    VAULT                VAULT OBJECT              SECRET NAME   SYNCHED   AGE
azurekeyvaultsecret.spv.no/registry-gitlab-secret-akv   mykeyvault   registry-gitlab-secrets                           70s
```
kubectl describe akvs registry-gitlab-secret-akv --> no event
I did something wrong or kubernetes.io/dockerconfigjson cannot be synced from AKV to K8S ?

**Comment by jackchuong** [comment]
I resolved it , for those who have the same question, here the steps:
1. Create a Deploy Token : follow this instruction for gitlab https://www.informaticsmatters.com/blog/2020/07/26/deploying-images-from-a-gitlab-registry.html
2. Create Azure Key Vault secret as json type , store above deploy token 
```
$string = '{"auths":{"registry.gitlab.com":{"username":"xxx","password":"xxx","email":"xxxx","auth":"xxx"}}}'
$Secret = ConvertTo-SecureString -String $string -AsPlainText -Force
Set-AzKeyVaultSecret -VaultName "keyvaultname" -Name "gitlabtokenjson" -SecretValue $Secret
```
3. Sync gitlab deploy token from AKV secret to K8S secret
```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: registry-gitlab-secret
spec:
  vault:
    name: mykeyvault # name of key vault
    object:
      name: gitlabtokenjson # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: registry-gitlab-secret # kubernetes secret name
      type: kubernetes.io/dockerconfigjson
      dataKey: .dockerconfigjson
```
