### ISSUE TITLE
[Question] Injecting multi value secrets (Docu)

### ISSUE THREAD

**Issue by habr-mms** [SparebankenVest/azure-key-vault-to-kubernetes#343]
I have a multi-value secret in my keyvault and want to inject it into a container.

Example secret:
```
username: user1
password: SuPeR_SECRET!
```

k8s manifest:
```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-credentials
  namespace: test
spec:
  vault:
    name: my-keyvault
    object:
      contentType: application/x-yaml
      name: db-credentials
      type: multi-key-value-secret
```

I can see that the secret was synchronized correctly
```
$ kubectl get akvs
NAME              VAULT         VAULT OBJECT      SECRET NAME       SYNCHED   AGE
db-credentials    my-keyvault   db-credentials    db-credentials    8s        1h
```

In the documentation I find only this blank page: https://akv2k8s.io/tutorials/env-injection/4-multi-value-secret/
How can I use the individual values from the secret in the container?
