### ISSUE TITLE
[Question]GlobalSign wildcard SSL not working

### ISSUE THREAD

**Issue by OwlDanny** [SparebankenVest/azure-key-vault-to-kubernetes#352]
I have successfully installed akv2k8s on my AKS cluster and linked it to my KeyVault. Your solution works perfectly with self-generated certificates in Azure Keyvault.

However, we have an integration with GlobalSign from Azure Keyvault for generating Wildcard OrganizationSSL certificates. Through this web I have requested (and received) an SSL certificate for *.sub.domain.com. So far so good.

I created a new AKVS yaml:

```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: api-ssl
  namespace: dev-back-end
spec:
  vault:
    name: my-ssl-keyvault
    object:
      name: gs-wc-ssl
      type: certificate
  output: 
    secret:
      name: gs-wc-ssl
      type: kubernetes.io/tls
```

deployed it to AKS

`azurekeyvaultsecret.spv.no/api-ssl created`

`kubectl get secrets -n dev-back-end` says that the secret is created with type kubernetes.io/tls

`kubectl get akvs -n dev-back-end` shows the connection, with a "synched" 27s ago and an age of 4m.

The interesting part is that the cert doesn't show up in the following command: 
`kubectl view-cert -n dev-back-end`
With the Azure Keyvault test certificate connected, it shows up here. So that's not good.

Let's "describe" the secret:
```
Name:         gs-wc-ssl
Namespace:    dev-back-end
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  5064 bytes
tls.key:  1675 bytes
```

Check the logs with `kubectl -n akv2k8s logs deployment/akv2k8s-controller`:
` 1 secret.go:125] "updating status for azurekeyvaultsecret" azurekeyvaultsecret="dev-back-end/api-ssl"`

Connected the cert to a NGINX Ingress rule and did a describe on that rule:
`  Warning  AddedOrUpdatedWithWarning  10m (x3 over 86m)  nginx-ingress-controller  Configuration for dev-back-end/back-end was added or updated ; with warning(s): TLS secret gs-wc-ssl is invalid: Failed to validate TLS cert and key: tls: private key does not match public key`

Can somebody please help me with this?

I exported the .CER file from Azure Keyvault en opened it in Windows:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/104504195/165519328-9b8ec275-93c9-4710-bddf-8ba9a5dc87df.png">
Maybe the chain is the problem? But how to fix this without losing the auto-renewal function with GlobalSign?
