### ISSUE TITLE
[BUG] Multiple AzureKeyVaultSecrets targeting the same Kubernets Secret are overwriting each other.

### ISSUE THREAD

**Issue by robinmanuelthiel** [SparebankenVest/azure-key-vault-to-kubernetes#37]
**Describe the bug**
As described here https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/36#issuecomment-593100498, defining multiple `AzureKeyVaultSecret` objects, which are targeting the same Kubernetes `Secret` are constantly overwriting each other.

**To Reproduce**

```yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: keyvault-secret-one
spec:
  vault:
    name: mykeyvault
    object:
      name: SecretOne
      type: secret
  output:
    secret:
      name: my-only-kuberentes-secret # <-- Same Kubernetes Secret targeted
      dataKey: secret-one
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: keyvault-secret-two
spec:
  vault:
    name: mykeyvault
    object:
      name: SecretTwo
      type: secret
  output:
    secret:
      name: my-only-kuberentes-secret # <-- Same Kubernetes Secret targeted
      dataKey: secret-two
```

**Expected behavior**

I would expect an error message in the logs or (best case) one secret with two values:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-only-kuberentes-secret
data:
  secret-one: XXXXXXXX
  secret-two: XXXXXXXX
```

Would be probably resolved, when implementing #36

**Comment by torresdal** [comment]
I'm thinking overwriting the `Secret` should be the default behavior, given a `AzureKeyVaultSecret` owns the `Secret`. If not we will get in trouble when/if you change the name of the `dataKey` in `AzureKeyVaultSecret` - it will add a new, instead of replacing.

To enable multiple `AzureKeyVaultSecret`'s writing different keys to the same `Secret`, I think we should introduce a new output type like `secret-multi-keys` (naming suggestions welcome!!). Using your example this would look like this:

```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: keyvault-secret-one
spec:
  vault:
    name: mykeyvault
    object:
      name: SecretOne
      type: secret
  output:
    secret-multi-keys:
      name: my-only-kuberentes-secret # <-- Same Kubernetes Secret targeted
      dataKey: secret-one
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: keyvault-secret-two
spec:
  vault:
    name: mykeyvault
    object:
      name: SecretTwo
      type: secret
  output:
    secret-multi-keys:
      name: my-only-kuberentes-secret # <-- Same Kubernetes Secret targeted
      dataKey: secret-two
```

What do you think @robinmanuelthiel ?
