### ISSUE TITLE
[FEATURE] Azure Workload Identity Support

### ISSUE THREAD

**Issue by pinkfloydx33** [SparebankenVest/azure-key-vault-to-kubernetes#378]
Azure recently added Azure Workload Identities (see https://github.com/Azure/azure-workload-identity and https://azure.github.io/azure-workload-identity/docs/) to AKS. It's currently technically in preview, but it is stable and there are many already using it in production. Currently in private-preview is support for managed identities (in addition to app registrations).

Important: This is the replacement to `aad pod-identity` and will be offered as a first-class add-on in AKS

**Describe the solution you'd like**
Support for Azure Workload Identity. I believe that this can be implemented on top of the existing environment-variable driven configuration with recognition of the new settings. I think it should *mostly* be handled by the azure client, though see linked issues below as there may be some monitoring that needs to occur.

We'd also need helm chart support to allow annotating service accounts, but I'll open that as a separate issue in the helm repo.

**Additional context**
See [cert-manager](https://github.com/cert-manager/cert-manager/issues/5085) and [external-dns](https://github.com/kubernetes-sigs/external-dns/issues/2724) for similar requests
See here for support in [go/auto-rest](https://github.com/Azure/go-autorest/pull/680)

**Comment by pinkfloydx33** [comment]
Any chance this will get looked at in the near future? For us, this (along with external-dns) is a blocker to complete adoption of workload identity. 

If not, would you accept a PR for it? I'm not an expert in go but I would be willing to give it a shot. Upon a quick glance, it looks like it may be a matter of some updates to `azure/credentialprovider`. Though while these are environment variable based settings, `azure/auth/EnvironmentSettings` doesn't include any new helpers for it (likely since it's a multistep process). So I *think* it'd require some manual switching on the precense of the appropriate variables, but perhaps that's not the best solution. It *may* also require an updated version of the azure clients, I'm not sure just yet. 

In either case, inspiration can be drawn from the [go-msal AZWI keyvault example](https://github.com/Azure/azure-workload-identity/tree/main/examples/msal-go) as well as KEDA's implementation linked in the OP.

**Comment by hargut** [comment]
As of October 24th 2022 the https://github.com/Azure/aad-pod-identity was as deprecated.

**Comment by weisdd** [comment]
Since I have some experience with making adal work well with federated identity, decided to give it a go for this project as well.
In my lab, controller was able to pull a secret. I still need to test injector (I'll probably have some time for that next week). If that scenario works as well, I'll prepare a PR.

**Comment by mohamedmzid** [comment]
hello @weisdd, glad to hear that's working with workload identity, could you share the branch/tag so that we can test from our side as well ?

**Comment by cgroschupp** [comment]
Hi @mohamedmzid,
i have linked my two PRs here.

This is my `value` file, please use the chart from my repo:
```
controller:
  image:
    repository: cgroschupp/akv2k8s-controller
    tag: workload-identity-support
  keyVaultAuth: environment
  logLevel: debug
  podLabels:
    azure.workload.identity/use: "true"
  serviceAccount:
    create: true
    labels:
      azure.workload.identity/use: "true"
    annotations:
      azure.workload.identity/client-id: <replace>
env_injector:
  enabled: false  
```
