### ISSUE TITLE
[Question] Is it possible to create additional entries besides username and password in basic-auth secret?

### ISSUE THREAD

**Issue by BenjaminHerbert** [SparebankenVest/azure-key-vault-to-kubernetes#379]
I want to create users for the ECK operator and prefill them from Azure KV by adding a secret like:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: rdeniro    # required field for kubernetes.io/basic-auth
  password: mypassword # required field for kubernetes.io/basic-auth
  roles: kibana_admin,ingest_admin  # optional, not part of kubernetes.io/basic-auth

```
[Further info about creating custom users in ECK](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html#k8s_native_realm).

I managed to create a _basic-auth_ secret with:

```yaml
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: elasticsearch-user
  namespace: ${namespace}
spec:
  vault:
    name: ${key_vault_name}
    object:
      name: elasticsearch-credentials
      type: secret
  output:
    secret:
      name: secret-basic-auth
      type: kubernetes.io/basic-auth

```
I could not find a way to do create a third entry `roles` which is required. Is it possible to create additional entries besides _username_ and _password_ as well, e.g. the _roles_ entry from above? A static setting would suffice.

**Comment by wimi** [comment]
Yes, you can do this using the `multi-key-value-secret` type of sync. You'll need to have all information in the secret as json or yaml.

```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-config
spec:
  vault:
    name: your-key-vault
    object:
      contentType: application/x-json # make sure this matches the content of the secret, can be either 'application/x-json' or 'application/x-yaml'
      name: db-config
      type: multi-key-value-secret
  output:
    secret:
      name: db-config
```

See more info here: https://akv2k8s.io/tutorials/sync/4-multi-key-value-secret/
