### ISSUE TITLE
[BUG] Inject Certificate not working in 1.3.1

### ISSUE THREAD

**Issue by srmars** [SparebankenVest/azure-key-vault-to-kubernetes#415]
Team,

We recently upgraded the akv2k8s from 1.3.0 to 1.3.1. After the upgrade Inject Certificate into application container not working

Reference:- https://akv2k8s.io/tutorials/env-injection/2-certificate/

```
    spec:
      containers:
      - name: akv2k8s-env-test
        image: spvest/akv2k8s-env-test:2.0.1
        args: ["PUBLIC_KEY", "PRIVATE_KEY"]
        env:
        - name: PUBLIC_KEY
          value: certificate-inject@azurekeyvault?tls.crt
        - name: PRIVATE_KEY
          value: certificate-inject@azurekeyvault?tls.key
```

Further checking in 1.3.1 release note there is bug fix happened for match valid injectable secret names [320](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/pull/320). I am suspecting this is causing this issue. From the below screen shot the updated regex is **not** picking the **certificate-inject@azurekeyvault?tls.key**

![image](https://user-images.githubusercontent.com/49336395/192743968-512df949-d4bf-475a-950c-a0a45e0f9abb.png)

With below regex its matching dot also 

`^([a-z-\d]*)@azurekeyvault([\?]?[a-z-\d\.]*)$ `

I am not regex expert :) . kindly check and fix the regex if needed. Thank you!
