### ISSUE TITLE
[BUG] old akv2k8s secrets left laying around

### ISSUE THREAD

**Issue by tspearconquest** [SparebankenVest/azure-key-vault-to-kubernetes#496]
**Note: Make sure to check out known issues (https://akv2k8s.io/troubleshooting/known-issues/) before submitting**

**Components and versions**
Select which component(s) the bug relates to with [X].

[ ] Controller, version: `x.x.x` (docker image tag)
[x] Env-Injector (webhook), version: `x.x.x` (docker image tag)
[ ] Other

**Describe the bug**
When creating jobs in a cluster running akv2k8s, a TLS secret is created in various namespaces. When a service such as gitlab's runners are running, it creates a temporary static Pod resource without an associated ReplicaSet or Deployment. If AKV2K8S environment injection is enabled on the namespace where these pods are deployed, it causes a secret for each pod to be created:

This can be seen with the below output I took from a test cluster with the gitlab runners:

```
kubectl get secret -n gitlab-runner |grep -E '^akv2k8s-runner-.*-project-[0-9]+-concurrent-[0-9][ ]*kubernetes[.]io[/]tls' |wc -l
     766
```

It's important to note that these temporary static Pod resources don't leverage any secrets from akv2k8s, and they don't get mutated by the webhook to include the initContainer; only pods tied to the gitlab runner deployment actually get the initContainer and use the secret.

**To Reproduce**
Install gitlab runner to a namespace with akv2k8s environment injection enabled and setup the gitlab runner deployment to use a secret from akv2k8s. Run some jobs, then check the output of `kubectl get secret -n <gitlab-runner-namespace>`

**Expected behavior**
Secrets for resources (pods) that don't get mutated should not be created. Secrets for resources (pods) that get mutated should be removed when the resource (pod) is removed from the API server.

**Additional context**

**Comment by tspearconquest** [comment]
https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/45f92f64dfba2708f4ebc557e1004487c58d4bb7/cmd/azure-keyvault-secrets-webhook/auth/auth.go#L260 is where the `ownerReferences` is set. `pod.GetOwnerReferences()` would of course return nothing since these pods have no ownerReferences themselves.

**Comment by tspearconquest** [comment]
I'm thinking something like should work:
```
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: false
    kind: Pod
    name: podname
```

**Comment by tspearconquest** [comment]
From looking at a secret created by the gitlab runner deployment with ownerReferences pointed at one of the auto-generated pods, it looks like we don't need `blockOwnerDeletion` or `controller`:

```
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: runner-e4wgkz1j-project-42151697-concurrent-0hln2c
    uid: 87426da4-f565-4d91-971a-da13cfe91b76
```
