### ISSUE TITLE
[FEATURE] Copying multiple secrets at once

### ISSUE THREAD

**Issue by Frankkkkk** [SparebankenVest/azure-key-vault-to-kubernetes#497]
Hi,
First of all thank you for this nice controller!

I wanted to use it to copy some kv secrets into k8s. In my case there are many secrets to copy (~30), so naturally it's a bit cumbersome to write 30 definitions.

I thought that we could maybe have a nicer way of representing many "syncs" from the **same vault** into the **same secret**.

Of course, as the semantics change, we'd need a new CRD.

For example, I'm thinking of something like this:
```yaml
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultMultipleSecrets
metadata:
  name: my-secrets
spec:
  vault:
    name: my-az-kv-vault
  output:
    secret:
      name: my-k8ssecret
  secrets:
  - secret1
  - secret2
  - secretn
```

What do you think ? If that looks somewhat okay for you, I'd be happy to make a PR !

Cheers,
