### ISSUE TITLE
datakey expected when output type 'kubernetes.io/tls' is used

### ISSUE THREAD

**Issue by EwanNoble** [SparebankenVest/azure-key-vault-to-kubernetes#5]
Manifest:
```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: my-cert
spec:
  vault:
    name: my-keyvault-name
    object:
      type: secret
      name: my-keyvault-secret-name
  output:
    secret:
      name: my-keyvault-secret-name
      type: kubernetes.io/tls
```

When applied the following Kubernetes logs occur:
`failed to get secret value for 'default/my-cert' from Azure Key vault 'my-keyvault-name' using object name 'my-keyvault-secret-name', error: no datakey spesified for output secret`

From the documentation it states that :
`dataKey: <required when type is opaque - name of the kubernetes secret data key to assign value to - ignored for all other types>` 

So my understanding is that this shouldn't be specified for my type:` kubernetes.io/tls`

**Comment by torresdal** [comment]
@EwanNoble I belive the certificate in AKV must be stored as a Certificate type and not as Secret, and object.type in spec must be `certificate`. So this spec should work (given you have a Certificate type in AKV):

```
spec:
  vault:
    name: my-keyvault-name
    object:
      type: certificate
      name: my-keyvault-secret-name
  output:
    secret:
      name: my-keyvault-secret-name
      type: kubernetes.io/tls
```

See this example in the docs: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes#certificate-with-exportable-key
