### ISSUE TITLE
[Question] valid naming convention

### ISSUE THREAD

**Issue by jasonrberk** [SparebankenVest/azure-key-vault-to-kubernetes#597]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Your question**
what are the valid characters used for the name?  I tried to create an AKVS with the name `my-app.my-secret-name@azurekeyvault` and the `.` broke injection

**To Reproduce**

create an env var like this in your deployment.yaml

```
- name: APP_INSIGHTS_INSTRUMENTATION_KEY
   value: {{ .Release.Name }}.instrumentation-key@azurekeyvault              # notice the "." separator
```

and a manifest like so:

```
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $.Release.Name }}.instrumentation-key           # notice the "." separator
  namespace: "{{ $.Release.Namespace }}"
spec:
  vault:
    name: "your-kv-name"
    object:
      type: secret
      name: instrumentation-key
```

**Logs**

nothing hard fails....the pods start up, but the raw string `my-app-name.instrumentation-key@azurekeyvault` is injected into the ENV var instead of the actual secret value

**Additional context**

given both the app name and secret name generally use kabob case, what character can we use to delineate the app name from the name of the secret it's using?  I tried `/` and `_` and got some helm issues:

> metadata.name: Invalid value: "my-app_my-secret-key": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

The dot worked from helm's point of view, but AKV2K8S seems to have issues with the dot.

For now, I'm using `--`.  For example `my-app-name--some-secret`
