### ISSUE TITLE
[Question] How to store akvs secret with data key:value secret rather than just name filed (similar to k8 secrets)

### ISSUE THREAD

**Issue by iamraj007** [SparebankenVest/azure-key-vault-to-kubernetes#598]
**Question**
Is there way to name(data field)  akvs secret be name something else like normal secret with data field like custom name something like dbuser/apikey/username etc?

**To Reproduce**
Create AzureKeyVaultSecret below
Try use this akvs in k8 cluster with data filed name something other then 'name'

```
# Sample akvs definition 
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: my-secrets-from-akv
#  username: dbadmin
spec:
  vault:
    name: AZ-VAULT-NAME
    object:
      name: Az-Vaule-Secret-NAME
      type: secret
```

```
# Sample expected secret with data filed to be consumed by apps (we know akv dont need to sync but App expect secret data named as username/url/password etc
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets-from-akv
type: Opaque
data:
  dbuser: DBuser123==
  dbapikey: APIkey123== 
```

Sample output that app expect though it remain in akvs
![image](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/assets/47947075/b0cb96db-ff3b-4bf4-87c3-4f16c2447a9c)

IS something like this is possible, observe insted of metedata.name ?
```
# Sample akvs definition 
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: my-secrets-from-akv
spec:
  vault:
    name: AZ-VAULT-NAME
    object:
      name: Az-Vaule-Secret-NAME   # kubernetes secret name
      dataKey: az-secret-*keyfiled*     # key to store object value in kubernetes secret
      type: secret
```

**Additional context**
Though something similar is possible but not looking to sync secret from azure to k8 (as they remain in base64) rather secret remain in akvs format but someway allow data filed with some user defined key:value data as secret.
Not sure if its possible, if any one have done it, please suggest. 
https://akv2k8s.io/tutorials/sync/1-secret/
