### ISSUE TITLE
[BUG] Regression in Env Injector breaks postgres deployments managed by CloudNativePg

### ISSUE THREAD

**Issue by johanra** [SparebankenVest/azure-key-vault-to-kubernetes#605]
**Components and versions**
[X] Env-Injector (webhook), version: `1.5.0`
[X] Helm Release (2.5.0)

**Describe the bug**
The latest release (1.5.0) of the env injector causes a problem when running postgres clusters with the [Cloudnative Postgres Operator](https://cloudnative-pg.io/). These postgres clusters work fine when using the previous release (1.4.0) which was installed with Helm Release (2.4.2)

**To Reproduce**

1. Install the CloudNative Postgres Operator using [helm](https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg) version 0.18.2 with the default values.
2. Setup a namespace "postgres-test" 
```
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-test
  labels:
    azure-key-vault-env-injection: enabled
```
3. then setup a postgres cluster in the postgres-test namespace 
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:13.12-6
  instances: 1
  storage:
    size: 1Gi
```
4. The CloudNative Operator will create a pod (postgres-1-initdb-......) which does not start with the following error message
`Error: container has runAsNonRoot and image has non-numeric user (nonroot), cannot verify user is non-root (pod: "postgres-1-initdb-5pq6x_bynubian-dev-02(edf17686-61ad-4165-b280-2a19c9400eda)", container: bootstrap-controller)`

**Expected behavior**
The pods started by the CloudNative Operator should start.

**Additional context**
Reverting the akv2k8s helm chart back to 2.4.2 which also reverts the env injector to 1.4.0 fixes the issue and postgres deployments are possible again
