### ISSUE TITLE
[Question] Why is the length of env var names limited?

### ISSUE THREAD

**Issue by trust56** [SparebankenVest/azure-key-vault-to-kubernetes#630]
**Your question**
The regex that is used to match the environment variables to substitute is having a length limit of 61 inside:
https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/ffbc2f58a93ec2cdae7dbc3ccff2cd4d7f2d8df5/cmd/azure-keyvault-env/environment.go#L12
Why is that?
It was introduced in version 1.5.0 (https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/pull/475). and upgrading to that version (from 1.4.0 for example) it breaks our use case, where we have way more longer environment variables. In previous versions it worked fine.
(However, the AzureKeyVaultSecret resources, that are referred by these environment variables are still working, Kubernetes is having no problem with very long resource names.
Thanks for your answer in advance :)

**To Reproduce**
1. Install akv2k8s of course :) And create a test namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  name: akv-test
  labels:
    azure-key-vault-env-injection: enabled
```
2. Create a AzureKeyVaultSecret resource with a short name, the environment variable of that will be substituted well:
```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: test-akvs-with-short-name
  namespace: akv-test
spec:
  vault:
    name: my-vault
    object:
      name: my-secert
      type: secret
```
3. Create another AzureKeyVaultSecret resource with a longer name:
```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: test-akvs-with-a-very-very-long-name-that-exceeds-a-certain-length-and-will-cause-the-regex-of-akv2k8s-not-to-match
  namespace: akv-test
spec:
  vault:
    name: my-vault
    object:
      name: my-secert
      type: secret
```
(Please note that both of the above AzureKeyVaultSecret resources themselves could be successfully created. No name length limitations apply here. )
4. Create a pod that tries to refer to both secrets, and print the environment variables after startup:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-akvs-pod
  namespace: akv-test
  labels:
    azure-key-vault-env-injection: enabled
spec:
  containers:
  - name: test-akvs-container
    image: spvest/akv2k8s-env-test:2.0.1
    command:
    - /bin/sh
    args:
    - -c
    - env | grep TEST_ENV
    env:
    - name: TEST_ENV_VAR_SHORT
      value: test-akvs-with-short-name@azurekeyvault
    - name: TEST_ENV_VAR_LONG
      value: test-akvs-with-a-very-very-long-name-that-exceeds-a-certain-length-and-will-cause-the-regex-of-akv2k8s-not-to-match@azurekeyvault
  restartPolicy: Never
```
5. View the logs of the pod with the following command:
```
kubectl --namespace akv-test logs test-akvs-pod --container test-akvs-container | grep ^TEST_ENV
```
Its output is:
```
TEST_ENV_VAR_SHORT=my-secret-value
TEST_ENV_VAR_LONG=test-akvs-with-a-very-very-long-name-that-exceeds-a-certain-length-and-will-cause-the-regex-of-akv2k8s-not-to-match@azurekeyvault
```
It would be great instead if both variables could contain the actual secret value.
6. Clean up the test namespace:
```
kubectl delete namespace akv-test
```
