### ISSUE TITLE
[Question] Can you inject a secret as part of a template?

### ISSUE THREAD

**Issue by BenRedmondBenham** [SparebankenVest/azure-key-vault-to-kubernetes#68]
Is it possible to inject something like this?

        - name: CONNECTION_STRING
          value: redis:6379,abortConnect=false,password=redispassword@azurekeyvault

In this case I need access to the password in other cases but also need to inject a connection string that contains the same password.

**Comment by thomscode** [comment]
@BenRedmondBenham,
I'm just getting started with this, and I don't know if this is possible or not. If it isn't you might consider something like this as an alternative.

```yaml
- name: REDIS_PASS
  value: redispassword@azurekeyvault
- name: CONNECTION_STRING
  value: redis:6379,abortConnect=false,password=$REDIS_PASS
```

**Comment by torresdal** [comment]
@BenRedmondBenham This will not work using env-injector. You can use the Controller, sync to a Kubernetes Secret, and reference the Kubernetes Secret the way @thomscode suggest (but using `redispassword@azurekeyvault` as in his example will not work).

**Comment by thomscode** [comment]
@torresdal,

Is this what you meant?

```yaml
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: 
spec:
  vault:
    name: myKV
    object:
      name: my-kv-secret-name
      type: secret
  output:
    secret:
      name: my-k8s-secret-name
      dataKey: redis-password

---
- name: REDIS_PASS
  valueFrom:
    secretKeyRef:
      name: my-k8s-secret-name
      key: redis-password
- name: CONNECTION_STRING
  value: redis:6379,abortConnect=false,password=$REDIS_PASS
```
