### ISSUE TITLE
[BUG] SecurityContext not supported

### ISSUE THREAD

**Issue by FrankCRoth** [SparebankenVest/azure-key-vault-to-kubernetes#73]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Describe the bug**
If a container is run as a different user defined by a SecurityContext the environment injection fails as the Init container does not start.

**To Reproduce**
I used the exmaples in the tutorial and added a securityContext section to the akvs-secret-app deployment. So it will look like the following now

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akvs-secret-app-run-as
  namespace: akv-test
  labels:
    app: akvs-secret-app-run-as
spec:
  selector:
    matchLabels:
      app: akvs-secret-app-run-as
  template:
    metadata:
      labels:
        app: akvs-secret-app-run-as
    spec:
      containers:
      - name: akv2k8s-env-test
        image: spvest/akv2k8s-env-test:2.0.1
        args: ["TEST_SECRET"]
        env:
        - name: TEST_SECRET
          value: "secret-inject@azurekeyvault" # ref to akvs
      securityContext:
        runAsUser: 100
```

**Expected behavior**
Init container started successfully and secret is made available to the pod

**Logs**
deployment logs:
Error from server (BadRequest): container "akv2k8s-env-test" in pod "akvs-secret-app-run-as-644d9cd75c-n4rbr" is waiting to start: PodInitializing

**Additional context**
