### ISSUE TITLE
[BUG] Getting "mapping values are not allowed in this context" with multi-key-value-secret

### ISSUE THREAD

**Issue by mimartin12** [SparebankenVest/azure-key-vault-to-kubernetes#737]
**Note: Make sure to check out known issues (https://akv2k8s.io/troubleshooting/known-issues/) before submitting**

**Components and versions**
Select which component(s) the bug relates to with [X].

[X] Controller, version: `2.6.0` (docker image tag)
[X] Env-Injector (webhook), version: `2.6.0` (docker image tag)
[ ] Other

**Describe the bug**
When using the example YAML from the documentation, or even my own, in an Azure Key Vault secret. I am able unable to get the secret to sync into the K8s cluster. When describing the `AzureKeyVaultSecret` resource, it shows this error.

```
  Warning  ErrAzureVault  25s (x18 over 86s)  azurekeyvaultcontroller  Failed to get secret for 'xxxxxxx' from Azure Key Vault 'cluster': yaml: mapping values are not allowed in this context
```
**To Reproduce**

1. Create Azure Key Vault Secret with YAML.
```yaml
key1: value1
key2: value2
key3: value3
```
![image](https://github.com/user-attachments/assets/e3a5f7ae-f38e-407f-87db-4dabb35b13bc)

2. Apply manifest
```yaml
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: cloud-credentials
spec:
  vault:
    name: xxxxxx
    object:
      name: xxxxxx
      type: multi-key-value-secret
      contentType: application/x-yaml
  output:
    secret: 
      name: cloud-credentials

```

**Expected behavior**

When applying the manifest, the Kubernetes secret is created.

**Logs**
If applicable, add logs to help explain your problem.

```
paste log here...
```

**Additional context**
