### ISSUE TITLE
[Question] Failed to get secret for 'certificate-sync' from Azure Key Vault '<KEYVAULT_NAME>'

### ISSUE THREAD

**Issue by Mishco** [SparebankenVest/azure-key-vault-to-kubernetes#75]
**Note: Make sure to check out known issues (https://github.com/sparebankenvest/azure-key-vault-to-kubernetes#known-issues) before submitting**

**Describe the bug**
Hello Guys, I have problem to create akvs and secret.

**To Reproduce**

I have this file, the same name as `akvs-certificate-sync.yaml`. On azure portal is also located valid certificate with name `cert-from-azure-portal`. And I follow instruction in wiki.

```yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: certificate-sync
  namespace: akv-test
spec:
  vault:
    name: "KEYVAULT_NAME" # name of key vault
    object:
      name: "cert-from-azure-portal"
      type: "certificate"
  output:
    secret:
      name: "cert-from_k8s" # kubernetes secret name
      type: kubernetes.io/tls # kubernetes secret type
```

```
> kubectl apply -f .\kubernetes\akvs-certificate-sync.yaml
azurekeyvaultsecret.spv.no/certificate-sync created
```

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

```
> kubectl describe -f .\kubernetes\akvs-certificate-sync.yaml
Name:         certificate-sync
Namespace:    akv-test
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"spv.no/v1alpha1","kind":"AzureKeyVaultSecret","metadata":{"annotations":{},"name":"certificate-sync","namespace":"akv-test"...
API Version:  spv.no/v1alpha1
Kind:         AzureKeyVaultSecret
Metadata:
  Creation Timestamp:  2020-04-30T09:25:36Z
  Generation:          1
  Resource Version:    10487268
  Self Link:           /apis/spv.no/v1alpha1/namespaces/akv-test/azurekeyvaultsecrets/certificate-sync
  UID:                 c5adca2b-aff0-411f-ad80-332760bb9216
Spec:
  Output:
    Secret:
      Name:  cert-from-azure-portal
      Type:  kubernetes.io/tls
  Vault:
    Name:  KEYVAULT_NAME
    Object:
      Name:  cert-from_k8s
      Type:  certificate
Events:
  Type     Reason         Age                 From                     Message
  ----     ------         ----                ----                     -------
  Warning  ErrAzureVault  41s (x2 over 101s)  azurekeyvaultcontroller  Failed to get secret for 'certificate-sync' from Azure Key Vault 'KEYVAULT_NAME'
```

Akvs is created, but is empty and has not create a secret:
```
> kubectl -n akv-test get akvs
NAME               VAULT                VAULT OBJECT                  SECRET NAME          SYNCHED
certificate-sync   KEYVAULT_NAME   cert-from-azure-portal
```

Do you have any advice ?

Thanks

**Additional context**
