### ISSUE TITLE
[BUG] Unable to determine the format of the secret created on k8s cluster

### ISSUE THREAD

**Issue by abudavis** [SparebankenVest/azure-key-vault-to-kubernetes#763]
We have installed akv2k8s on Openshift 4.14 using the yaml below:
We have created an object type "Key" called "dummy" (generated as RSA) on Azure Key Vault on Azure cloud.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
  name: argocdapp-akv2k8s
  namespace: openshift-gitops
spec:
  destination:
    namespace: akv2k8s
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: akv2k8s
    helm:
      parameters:
        - name: global.keyVaultAuth
          value: environment
        - name: controller.enabled
          value: 'true'
        - name: controller.metrics.enabled
          value: 'true'
        - name: env_injector.enabled
          value: 'false'
        - name: controller.securityContext.allowPrivilegeEscalation
          value: 'false'
        - name: global.env.AZURE_TENANT_ID
          value: xxxx
        - name: global.env.AZURE_CLIENT_ID
          value: xxxx
        - name: global.env.AZURE_CLIENT_SECRET
          value: xxxx
      releaseName: akv2k8s
    repoURL: 'https://charts.spvapi.no'
    targetRevision: 2.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
```

Then we went on to create the AzureKeyVaultSecret yaml which created a secret called "dummy" on openshift:

```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: dummy
  namespace: ace
spec:
  vault:
    name: company-test-vault
    object:
      name: dummy # name of the akv object
      type: key # akv object type
  output:
    transform: # optional transformers executed in listed order
      - trim # optional - trims empty space
      #- base64encode # optional - encode to base64
      #- base64decode # optional - decode from base64
    secret:
      name: dummy # kubernetes secret name
      dataKey: key # key to store object value in kubernetes secret

```
Please let me know in what format akv2k8s generated the openshift secret data shown below for "dummy" secret (I downloaded this as a file from the akv2k8s created openshift secret), at this point it is unusable anywhere.
```
��>
�^D�=W�x`t�����Ɂ��H�/i�Y��*����$K*m��Rfp	���wy�1!_��A���I�8���'�L�gۓG��҃����b=RM|in�t��]~��"E��$�$H�?����K%y������9k�fY�!�}�K��h{m�I�(Dx|�4���p��3+��C��.~,�Ak�(���w�<wN��T����g��5$y�~��&`d'KGJ�w���F�,,���8׻�*GR5
```

The resultant secret "dummy" looks like this:

```
kind: Secret
apiVersion: v1
metadata:
  name: dummy
  namespace: ace
  uid: 513b7398-cf26-4914-8b48-91938c6bf246
  resourceVersion: '188203623'
  creationTimestamp: '2024-10-04T12:54:30Z'
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  ownerReferences:
    - apiVersion: spv.no/v2beta1
      kind: AzureKeyVaultSecret
      name: dummy
      uid: 0a3133d3-2ed2-4d3f-97a6-0cc4ba162a72
      controller: false
      blockOwnerDeletion: true
data:
  key: 4cUUPgr/XkQHtX89V4h4YHS+9eK8HsrJgerNSIAvacsTWZnUKsLAgv0kSyptEfXiUh9mcAmlj+93edAxIV+z1EHD/tZJ9jgTDLDppScc10zeZ9uTR6HsBNKDg8bw1WI9UgZNBXxpbu90FYuYXQx+vRCcIhRF5OkkwyRIrz/U2+KySyV5GeIV6tYVksgdEgf9OWvtZlnjIZscfZhL86QTB2h7bYFJEqwoRAx4fPM04RvU0nDj/jMrue0QQ/64Ln4HLAPqQWu5KOfc0XeIPHdO7IMZVPrDzutnwJE1JAd5rX7j5iZgZCdLR0rfD3fgvu9G2iwss8EWmjjXu40qR1I1EQ==
type: Opaque
```
