### ISSUE TITLE
[Question] How to pull a repository by injecting a git token

### ISSUE THREAD

**Issue by p3tric** [SparebankenVest/azure-key-vault-to-kubernetes#83]
Hi, thank you for this great project. I have a question regarding pulling a repository from Azure by injecting an Azure Key Vault secret .

I am storing my git token in Azure Key Vault and trying to pull a repository using this token as follows:

```
        - name: git-app
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://$(TOKEN)@dev.azure.com<my-azure-repository-address>
          env:
          - name: TOKEN
            value: "git-token@azurekeyvault"
```

When I try to run this I get the following error:

`fatal: unable to access 'https://azurekeyvault@dev.azure.com....': Could not resolve host: azurekeyvault@dev.azure.com`

So, if I understood correctly it cannot resolve the repository hostname because of the env value. Is there a way to overcome this problem?

Thank you for your help.
