### ISSUE TITLE
[Question] Is it possible to get multiple secrets in one template?

### ISSUE THREAD

**Issue by prabhavgupta** [SparebankenVest/azure-key-vault-to-kubernetes#93]
**Your question**
Is it possible to get multiple secrets in one template?

**To Reproduce**
Using a template like this,
```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync
  namespace: {{ .Values.nameSpaceName }}
spec:
  vault:
    name: {{ .Values.keyVaultName }}
    object:
      name: test1
      type: secret
      name: test2
      type: secret
  output:
    secret:
      name: a
      dataKey: secret-value
      name: b
      dataKey: secret-value
```

**Additional context**
When using the above template, I can only see one secret which is the last in the output, 'b' in this case.

**Comment by gaurav-magassian** [comment]
I believe CRD does not support an array of secrets as per documentation 
https://akv2k8s.io/reference/

**Comment by vidarw** [comment]
I think @gaurav-magassian is correct here. The closest you get is probably to use a multi-key-value secret:

Content in KeyVault:
```
{
  "tenantId": "xxx",
  "subscriptionId": "xxx",
  "resourceGroup": "xxx",
  "aadClientId": "xxx",
  "aadClientSecret": "xxx"
}

```
KeyVault Secret:
```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: azure-dns-credentials
spec:
  vault:
    name: xxx
    object:
      type: multi-key-value-secret
      name: azure-dns-credentials
      contentType: application/x-json 
  output:
    secret:
      name: azure-dns-credentials
```

Resulting secret
```yaml
apiVersion: v1
data:
  aadClientId: xxx
  aadClientSecret: xxx
  resourceGroup: xxx
  subscriptionId: xxx
  tenantId: xxx
kind: Secret
```

This also work with multi-line secrets in the keyvault.
