### ISSUE TITLE
Unable to process complex JSON string as a Secret

### ISSUE THREAD

**Issue by gaurav-magassian** [SparebankenVest/azure-key-vault-to-kubernetes#96]
**Question**
Unable to create secret of contentType application/x-json - **cannot unmarshal object into Go value of type string, requeuing**

The end goal is to deploy secret as kubernetes.io/dockerconfigjson which failed hence tried, baby steps.

**Version:** spvest/azure-keyvault-controller:1.0.2

**To Reproduce**
Following is the definition of AzureKeyVaultSecret
```
kind: AzureKeyVaultSecret 
metadata: 
  name: test-123 
spec: 
  vault: 
    name: my-vault # Key vault on azure 
    object: 
      name: my-secret 
      type: multi-key-value-secret # akv object type 
      contentType: application/x-json 
  output: 
    secret: 
      name: test-123 # kubernetes secret name 
```
Secret value/text in AKV 
```
{
  "i": "3",
  "S": {
    "phone": {
      "sales": "2223334444"
    }
  }
}
```

**Logs**
```
time="2020-07-20T11:45:23Z" level=error msg="error syncing 'default/test-123': failed to get secret from Azure Key Vault for secret 'default'/'test-123 ', error: json: cannot unmarshal object into Go value of type string, requeuing"
```

**Additional Information**
I do not face any issue when I process simple json object like below
```
{
  "name": "John",
  "country": "Wonderland",
  "city": "Unidentified",
  "reason": "Loss of Identity"
}
```

**Comment by vidarw** [comment]
I do not clearly see how more complex objects like the nested structure or arrays should be treated in a way that makes sense as a Kubernetes secret. What would be the expected outcome of the example you provided?

The multi-key-value-secret creates an opaque secret where each key in the JSON object results in a corresponding key under the data object. I think the `data` section of the secret is considered a key-value map without the possibility to store complex json.
If you want a more complex data structures passed on to your application as secrets, I suggest just pushing the entire JSON as a string.

**Comment by gaurav-magassian** [comment]
Thanks @vidarw for the response.

I am trying to create a docker image pull secret where 
I am pushing .docker/config.json using (following the format specified at [link](https://akv2k8s.io/reference/azure-key-vault-secret/#kubernetesiodockerconfigjson) )
```
az keyvault secret set --name my-secret --vault-name my-vault --file .docker/config.json
```
Once pushed successfully, I am trying to install using
```
kind: AzureKeyVaultSecret 
metadata: 
  name: test-123 
spec: 
  vault: 
    name: my-vault # Key vault on azure 
    object: 
      name: my-secret 
      type: multi-key-value-secret # akv object type 
      contentType: application/x-json 
  output: 
    secret: 
      name: test-123 # kubernetes secret name 
      type: kubernetes.io/dockerconfigjson
```
And, I get the following error. I am following the documentation and not sure what I am doing wrong  
```
time="2020-07-20T11:45:23Z" level=error msg="error syncing 'default/test-123': failed to get secret from Azure Key Vault for secret 'default'/'test-123 ', error: json: cannot unmarshal object into Go value of type string, requeuing"
```

**Comment by vidarw** [comment]
Tried to set the `spec.vault.object.type` to `secret` instead? If that don't work, we need to investigate further and I think it might be correct to report the problem as a bug.

**Comment by gaurav-magassian** [comment]
@vidarw that woked like a charm. Days saved. Updating resource file for anyone looking for solution

```
kind: AzureKeyVaultSecret 
metadata: 
  name: test-123 
spec: 
  vault: 
    name: my-vault # Key vault on azure 
    object: 
      name: my-secret 
      type: secret # akv object type 
      contentType: application/x-json 
  output: 
    secret: 
      name: test-123 # kubernetes secret name 
      type: kubernetes.io/dockerconfigjson
```
